"""
Lexical memory store backed by the hybrid retrieval engine.

Routes memory search through the hybrid engine (BM25 + TF-IDF fused and
reranked with lexical features) rather than raw keyword overlap. This improves
ordering for exact and near-exact matches but does NOT provide semantic
paraphrase recall — the engine cannot match queries that share no vocabulary
with the stored memory. For true semantic recall, enable RAG_EMBEDDINGS_ENABLED
with memory embeddings generated by an Ollama model.

Falls back to the repository's keyword search if anything goes wrong.
"""
from app.db.repositories import repo


class BasicVectorStore:
    """Interface-compatible semantic store backed by the hybrid search engine."""

    async def semantic_search(self, project_id: str, user_id: str, query: str, limit: int = 5):
        if not query or not query.strip():
            return []
        try:
            from app.memory.hybrid_search import engine

            rows = await repo.list_memories(project_id, user_id)
            if not rows:
                return []
            documents = [{**row, "text": row.get("text", "")} for row in rows]
            results = engine.search(query, documents, top_k=limit)
            return [{**r.doc, "score": round(r.score, 4)} for r in results]
        except Exception:
            return await repo.search_memories(project_id, user_id, query, limit=limit)


vector_store = BasicVectorStore()
